name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for submitting this issue and welcome!\nWe are glad that you are here and we appreciate your contributions."
        pr-message: "Thank you for the contribution and welcome!\nWe are glad that you are here and we appreciate your contributions."
